helm:
  parameters:
  - name: mealie.controllers.mealie.containers.main.image.repository
    value: ghcr.io/mealie-recipes/mealie
    forcestring: true
  - name: mealie.controllers.mealie.containers.main.image.tag
    value: v3.4.0
    forcestring: true
