helm:
  parameters:
  - name: image.name
    value: vikunja/vikunja
    forcestring: true
  - name: image.tag
    value: 1.1.0
    forcestring: true
  - name: vikunja.controllers.vikunja.containers.main.image.repository
    value: 1.1.0
    forcestring: true
