helm:
  parameters:
  - name: openwebui.controllers.openwebui.containers.main.image.repository
    value: backplane/open-webui
    forcestring: true
  - name: openwebui.controllers.openwebui.containers.main.image.tag
    value: 0.8.0
    forcestring: true
