helm:
  parameters:
  - name: openwebui.controllers.openwebui.containers.main.image.repository
    value: ghcr.io/open-webui/open-webui
    forcestring: true
  - name: openwebui.controllers.openwebui.containers.main.image.tag
    value: v0.10.0
    forcestring: true
