helm:
  parameters:
  - name: lemonade.controllers.lemonade.containers.main.image.repository
    value: ghcr.io/lemonade-sdk/lemonade-server
    forcestring: true
  - name: lemonade.controllers.lemonade.containers.main.image.tag
    value: v11.8.0
    forcestring: true
