helm:
  parameters:
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
    value: ghcr.io/linuxserver/sabnzbd
    forcestring: true
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.tag
    value: latest@sha256:219f9d2508849a916614840e48bc0d09769724a0bd2cb031d42572cdefc23c04
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.repository
    value: ghcr.io/linuxserver/radarr
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.tag
    value: latest@sha256:7e9dbd55e29496f66fd8f3e210e5c202c1437ba8f4a748013c6da8ac268a0de1
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.repository
    value: ghcr.io/linuxserver/sonarr
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.tag
    value: latest@sha256:cefa1c97ba8f5db60c1c89d04015ead764d3b850b4fbdc5784bdde2a02d72350
    forcestring: true
