helm:
  parameters:
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
    value: ghcr.io/linuxserver/sabnzbd
    forcestring: true
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.tag
    value: latest@sha256:371fd7665789ee0c1961c4d15bbd43d85ef2af0145c0e740c505ccd4fff72d16
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.repository
    value: ghcr.io/linuxserver/radarr
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.tag
    value: latest@sha256:7eb64f5af8bbe48e79bc55c0c37ca8db89b2f073a9ff0094f603916ae1df9de8
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.repository
    value: ghcr.io/linuxserver/sonarr
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.tag
    value: latest@sha256:1a90192952c30f9420994b2e2171083ea8cae100357de5e9eb25890efa90a6ce
    forcestring: true
