helm:
  parameters:
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
    value: ghcr.io/linuxserver/sabnzbd
    forcestring: true
  - name: sabnzbd.controllers.sabnzbd.containers.main.image.tag
    value: latest@sha256:7afe3af1cff19c2a7a5d4bacb2202fcb21a0ee15b7e23e4114ab3f7070213662
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.repository
    value: ghcr.io/linuxserver/radarr
    forcestring: true
  - name: radarr.controllers.radarr.containers.main.image.tag
    value: latest@sha256:b2d2bc9bafb76073d96142bda07ea90c6d6afd9207fe4ff2d4f9d3b50fcdbd76
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.repository
    value: ghcr.io/linuxserver/sonarr
    forcestring: true
  - name: sonarr.controllers.sonarr.containers.main.image.tag
    value: latest@sha256:47ce6f3b2afb17c12b393da2fefb11718f15cd1308baeba1cb61cbbbb9c5aedc
    forcestring: true
