helm:
  parameters:
  - name: vw.controllers.main.containers.main.image.repository
    value: ghcr.io/dani-garcia/vaultwarden
    forcestring: true
  - name: vw.controllers.main.containers.main.image.tag
    value: 1.34.3
    forcestring: true
