trivy-operator:
  deploy: false
  operator:
    scanJobsConcurrentLimit: 3
    batchDeleteLimit: 5
    scanJobsRetryDelay: 90s
    scanJobTTL: "24h"
    scanSecretTTL: "24h"
    sbomGenerationEnabled: false
    clusterComplianceEnabled: false
    configAuditScannerEnabled: false
    infraAssessmentScannerEnabled: false
  trivyOperator:
    useGCRServiceAccount: false
    scanJobAffinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                vulnerabilityReport.scanner: Trivy
            topologyKey: kubernetes.io/hostname
  trivy:
    ignoreUnfixed: false
    timeout: "10m0s"
    # -- resources resource requests and limits for scan job containers
    resources:
      requests:
        cpu: 100m
        memory: 128M
        ephemeralStorage: "512Mi"
      limits:
        cpu: 4000m
        memory: 1500M
        ephemeralStorage: "512Mi"