trivy-operator:
  deploy: true
  excludeNamespaces: "tvk"
  operator:
    scanJobsConcurrentLimit: 3
    batchDeleteLimit: 5
    scanJobsRetryDelay: 120s
    configAuditScannerEnabled: false
    rbacAssessmentScannerEnabled: false
    infraAssessmentScannerEnabled: false
    clusterComplianceEnabled: false
    sbomGenerationEnabled: false
  trivyOperator:
    useGCRServiceAccount: false
    # scanJobAffinity:
    #   podAntiAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       - labelSelector:
    #           matchLabels:
    #             vulnerabilityReport.scanner: Trivy
    #         topologyKey: kubernetes.io/hostname
    scanJobNodeSelector:
      kubernetes.io/hostname: thor
    scanJobTolerations:
      - key: "workload"
        value: "thor"
        operator: "Equal"
        effect: "NoSchedule"
  trivy:
    severity: UNKNOWN,MEDIUM,HIGH,CRITICAL
    slow: true
    ignoreUnfixed: false
    timeout: "10m0s"
    # -- resources resource requests and limits for scan job containers
    resources:
      requests:
        cpu: 100m
        memory: 128M
        ephemeralStorage: "512Mi"
      limits:
        cpu: 4000m
        memory: 1500M
        ephemeralStorage: "512Mi"
    server:
      # -- resources set trivy-server resource
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
          ephemeralStorage: "256Mi"
        limits:
          cpu: 2
          memory: 1Gi
          ephemeralStorage: "256Mi"