helm:
  parameters:
  - name: bentopdf.controllers.bentopdf.containers.main.image.repository
    value: ghcr.io/alam00000/bentopdf-simple
    forcestring: true
  - name: bentopdf.controllers.bentopdf.containers.main.image.tag
    value: v2.3.3
    forcestring: true
