helm:
  parameters:
  - name: plex.controllers.main.containers.main.image.repository
    value: plexinc/pms-docker
    forcestring: true
  - name: plex.controllers.main.containers.main.image.tag
    value: 1.18.4.2171-ac2afe5f8
    forcestring: true
