helm:
  parameters:
  - name: plex.controllers.main.containers.main.image.repository
    value: plexinc/pms-docker
    forcestring: true
  - name: plex.controllers.main.containers.main.image.tag
    value: 1.23.1.4571-6119e8eed
    forcestring: true
