{{- if .Values.lemonade.deploy }}
apiVersion: v1
data:
  config.json: |-
    {
      "cloud_providers": [],
      "config_version": 2,
      "ctx_size": -1,
      "disable_model_filtering": false,
      "enable_dgpu_gtt": false,
      "extra_models_dir": "",
      "flm": {
        "args": ""
      },
      "global_timeout": 600,
      "host": "0.0.0.0",
      "kokoro": {
        "cpu_bin": "builtin"
      },
      "llamacpp": {
        "args": "",
        "backend": "vulkan",
        "cpu_args": "",
        "cpu_bin": "builtin",
        "cuda_bin": "builtin",
        "prefer_system": true,
        "rocm_args": "",
        "rocm_bin": "builtin",
        "vulkan_args": "",
        "vulkan_bin": "builtin"
      },
      "log_level": "debug",
      "max_loaded_models": -1,
      "models_dir": "auto",
      "moonshine": {
        "args": "",
        "cpu_args": "",
        "cpu_bin": "builtin"
      },
      "no_broadcast": false,
      "no_fetch_executables": false,
      "offline": false,
      "port": 13305,
      "rocm_channel": "stable",
      "ryzenai": {
        "server_bin": "builtin"
      },
      "sdcpp": {
        "args": "",
        "backend": "auto",
        "cfg_scale": 7.0,
        "cpu_args": "",
        "cpu_bin": "builtin",
        "height": 512,
        "rocm_args": "",
        "rocm_bin": "builtin",
        "steps": 20,
        "vulkan_args": "",
        "vulkan_bin": "builtin",
        "width": 512
      },
      "vllm": {
        "args": "",
        "backend": "auto"
      },
      "websocket_port": "auto",
      "whispercpp": {
        "args": "",
        "backend": "auto",
        "cpu_args": "",
        "cpu_bin": "builtin",
        "npu_args": "",
        "npu_bin": "builtin"
      }
    }
kind: ConfigMap
metadata:
  name: lemonade-config
  namespace: {{ $.Release.Namespace }}

{{- end }}