helm:
  parameters:
  - name: donetick.controllers.donetick.containers.main.image.repository
    value: donetick/donetick
    forcestring: true
  - name: donetick.controllers.donetick.containers.main.image.tag
    value: v0.1.60
    forcestring: true
