donetick:
  defaultPodOptions:
    automountServiceAccountToken: false
    dnsConfig:
      options:
        - name: ndots
          value: "3"
    labels:
      application: donetick
    securityContext:
      runAsUser: 65534
      fsGroup: 65534
      fsGroupChangePolicy: "Always"
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  controllers:
    donetick:
      type: deployment
      annotations:
        secrets.infisical.com/auto-reload: "true"
      initContainers:
        copy-config:
          image:
            repository: "quay.io/prometheus/busybox"
            tag: "latest"
            pullPolicy: Always
          command: ["sh", "-c", "if [[ ! -f '/config/selfhosted.yaml' ]]; then cp /app/config/selfhosted.yaml /config/selfhosted.yaml && chown 65534:65534 /config/selfhosted.yaml && echo 'Configuration set'; else echo 'Configuration exists, nothing to do';fi"]
      containers:
        main:
          image:
            repository: donetick/donetick
            tag: "v0.1.53"
            pullPolicy: IfNotPresent
          env:
            TZ: "America/New_York"
            DT_ENV: "selfhosted"
            DT_SQLITE_PATH: "/donetick-data/donetick.db"
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: "1"
              memory: 768Mi
            requests:
              cpu: 500m
              memory: 256Mi
  service:
    app:
      controller: donetick
      annotations:
        traefik.ingress.kubernetes.io/service.serversscheme: http
        traefik.ingress.kubernetes.io/service.passhostheader: "true"
      ports:
        http:
          enabled: true
          primary: true
          port: 2021
          protocol: HTTP
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: le-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
      hosts:
        - host: todo.xtr.pub
          paths:
            - path: /
              pathType: ImplementationSpecific
              service:
                identifier: app
                port: http
      tls:
      - hosts:
        - todo.xtr.pub
        secretName: tls-secret
  persistence:
    config:
      enabled: true
      type: persistentVolumeClaim
      storageClass: ec-gold
      accessMode: ReadWriteOnce
      size: "512Mi"
      globalMounts:
        - path: /config
    data:
      enabled: true
      type: persistentVolumeClaim
      storageClass: ec-gold
      accessMode: ReadWriteOnce
      size: "512Mi"
      advancedMounts:
        donetick:
          main:
            - path: /donetick-data
    app-config:
      enabled: true
      type: custom
      volumeSpec:
        secret:
          secretName: app-config
      globalMounts:
        - path: /app/config

  networkpolicies:
    main:
      enabled: false
      controller: donetick
      policyTypes:
        - Ingress
        - Egress
      rules:
        ingress:
          - from:
              - namespaceSelector:
                  matchLabels:
                    name: traefik
                podSelector:
                  matchLabels:
                     app.kubernetes.io/name: traefik
        egress:
          - to:
              - namespaceSelector: {}
                podSelector:
                  matchLabels:
                    k8s-app: kube-dns
            ports:
              - port: 53
                protocol: UDP
          # - to:
          #     - ipBlock:
          #         cidr: 0.0.0.0/0

infisicalSecret:
  app-config:
    syncInterval: 120