helm:
  parameters:
  - name: tautulli.controllers.tautulli.containers.main.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.controllers.tautulli.containers.main.image.tag
    value: v2.17.2-ls233
    forcestring: true
