helm:
  parameters:
  - name: tautulli.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.image.tag
    value: latest@sha256:edaa802c62f30527e97648bd4faf645f748f1906369b42a6d3341e9dc7c98b40
    forcestring: true
