helm:
  parameters:
  - name: tautulli.controllers.tautulli.containers.main.image.repository
    value: ghcr.io/linuxserver/tautulli
    forcestring: true
  - name: tautulli.controllers.tautulli.containers.main.image.tag
    value: develop-fe245b11-ls456
    forcestring: true
