---
apiVersion: v1
kind: Service
metadata:
  name: s3-http
  annotations:
    traefik.ingress.kubernetes.io/service.nativelb: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: http
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  ports:
    - name: s3-api
      port: 9000
      targetPort: 9000
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: s3-http
  labels:
    kubernetes.io/service-name: s3-http
addressType: IPv4
ports:
  - name: s3-api
    appProtocol: http
    port: 9000
endpoints:
  - addresses:
      - "192.168.30.20"
    conditions:
      ready: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: s3-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: le-prod
spec:
  ingressClassName: traefik
  rules:
  - host: s3.xtr.pub
    http:
      paths:
      - backend:
          service:
            name: s3-http
            port:
              name: s3-api
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - s3.xtr.pub
    secretName: tls-secret-s3