apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    accessControlAllowMethods:
    - GET
    - OPTIONS
    - PUT
    accessControlMaxAge: 100
    addVaryHeader: true
    browserXssFilter: true
    contentTypeNosniff: true
    customFrameOptionsValue: SAMEORIGIN
    forceSTSHeader: true
    frameDeny: true
    referrerPolicy: same-origin
    sslRedirect: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    contentSecurityPolicy: |
      default-src 'none'; form-action 'none'; frame-ancestors 'none'; base-uri 'none'
    hostsProxyHeaders:
      - "X-Forwarded-Host"
    permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=()"
    customResponseHeaders:
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex," # disable search engines from indexing home server
      server: "" # hide server info from visitors