apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: tls13
  namespace: {{ .Release.Namespace }}
spec:
  minVersion: VersionTLS13
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true