helm:
  parameters:
  - name: babybuddy.controllers.babybuddy.containers.main.image.repository
    value: ghcr.io/linuxserver/babybuddy
    forcestring: true
  - name: babybuddy.controllers.babybuddy.containers.main.image.tag
    value: 2.7.1
    forcestring: true
