k8s-triliovault-operator:
  deploy: true
  replicaCount: 1
  installTVK:
    enabled: false
  image:
    pullPolicy: IfNotPresent

tvkvaultmanager:
  enabled: true
  ingressConfig:
    host: "tvk.xtr.pub"
    annotations:
      cert-manager.io/cluster-issuer: le-prod
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
  instanceName: conrad
  license:
    name: trilio-license
    key: xYENDgwKD3jajVHLboMwELz7Kyz1bNVgJ0AkDnkgtWqSViLkvjaLajUBZCBq/r6mHBpBFHVOK689M555SruS7sBS4VGfL6RYiJkbfEnWFqE1VbmBFukf4n7JuGDCI0lu+ht0hHgFjdEEdGsuSCfb1nZITkZj2eARbXPLEPtkB6ZssYRSY/JdG3sdDPS6EeNO2lmrzjWU1wnz/nlJGX2pzrgF5abEfqGlKzcNjvbdWaF9L7LGyd68Yx5J0V7Qvm7GlIWPUcilYKhmikl0BiDwgWmMIoU8CqWvSJrs6R3E7pzlRRBI6SHDQnPmeYhMzULBuNYygKjIZYhkO6Qxlo8Px2W2PQwc87n/kOM3LJj0cZvbR2f1JzT4oNJUVzXe+Yo+dU3rUuvXOXnrFGaTsP6Z1hpq0KYd1xd7c07XH1nzA7+CodQwLQIVAIrt9hMFwGKfa1jQP24VwQMbXNAxAhQgO8Jhcijtr0kvzfK+ZYcyLP/8Fw==X02g0