apiVersion: v1
name: cert-manager
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
keywords:
  - cert-manager
  - kube-lego
  - letsencrypt
  - tls
sources:
  - https://github.com/jetstack/cert-manager
version: v1.12.7
dependencies:
- name: cert-manager
  version: "v1.12.7"
  condition: cert-manager.platform.deploy
  repository: "@jetstack"