helm:
  parameters:
  - name: overseerr.controllers.overseer.containers.main.image.repository
    value: ghcr.io/linuxserver/overseerr
    forcestring: true
  - name: overseerr.controllers.overseer.containers.main.image.tag
    value: latest@sha256:1c141ae4fd6e07bf4afa157360c64d8f1a4aed56cf964f79f9db86ca588cd2ab
    forcestring: true
