helm:
  parameters:
  - name: overseerr.controllers.overseer.containers.main.image.repository
    value: ghcr.io/linuxserver/overseerr
    forcestring: true
  - name: overseerr.controllers.overseer.containers.main.image.tag
    value: latest@sha256:ad4c6a173bc0f5e1ff9bfa4169fe232fd6556796677d30daa455f6348093a3d5
    forcestring: true
