helm:
  parameters:
  - name: overseerr.controllers.overseer.containers.main.image.repository
    value: ghcr.io/linuxserver/overseerr
    forcestring: true
  - name: overseerr.controllers.overseer.containers.main.image.tag
    value: latest@sha256:c5f3c0c246f121b5e4bc8cda2b6e22806f1e1443fc4235c3c050e5b09ae8eda7
    forcestring: true
