helm:
  parameters:
  - name: actual.controllers.actual.containers.main.image.repository
    value: ghcr.io/actualbudget/actual
    forcestring: true
  - name: actual.controllers.actual.containers.main.image.tag
    value: 26.2.1
    forcestring: true
