helm:
  parameters:
  - name: searxng.controllers.searxng.containers.main.image.repository
    value: searxng/searxng
    forcestring: true
  - name: searxng.controllers.searxng.containers.main.image.tag
    value: 2026.5.26-3db8b424a
    forcestring: true
