helm:
  parameters:
  - name: searxng.controllers.searxng.containers.main.image.repository
    value: searxng/searxng
    forcestring: true
  - name: searxng.controllers.searxng.containers.main.image.tag
    value: 2026.7.28-c01178d03
    forcestring: true
