apiVersion: v2
name: searxng
version: 1.0.0
dependencies:
  - name: app-template
    version: 3.4.0
    repository: "@bjws"
    alias: searxng
    condition: searxng.deploy
  - name: valkey
    version: 0.7.6
    repository: "@valkey"
    condition: searxng.deploy