apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-deployments
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:erkerb4/home-k8s-gitops.git
      revision: HEAD
      directories:
      - path: apps/infrastructure/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        notifications.argoproj.io/subscribe.app-outofsync.slack: argo
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
      source:
        repoURL: git@github.com:erkerb4/home-k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
