apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: internal-apps-deployments
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:erkerb4/home-k8s-gitops.git
      revision: HEAD
      directories:
      - path: apps/internal-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        notifications.argoproj.io/subscribe.app-outofsync.slack: argo
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo

        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main:image-updater-{{.SHA256}}
        argocd-image-updater.argoproj.io/image-list: actual=ghcr.io/actualbudget/actual:~25.x,babybuddy=ghcr.io/linuxserver/babybuddy:~2.4,meilisearch=getmeili/meilisearch:~v1.8.x,barlie-redis=redis:~7.2,barlie-assistant=barassistant/server:~3.14,barlie-sr=barassistant/salt-rim:~2.12,changed=ghcr.io/dgtlmoon/changedetection.io:~0.45,mealie=ghcr.io/mealie-recipes/mealie:~v3,sabnzbd=ghcr.io/linuxserver/sabnzbd:latest,radarr=ghcr.io/linuxserver/radarr:latest,sonarr=ghcr.io/linuxserver/sonarr:latest,tautulli=ghcr.io/linuxserver/tautulli:latest,donetick=donetick/donetick:~v0.1

        argocd-image-updater.argoproj.io/actual.helm.image-name: actual.controllers.actual.containers.main.image.repository
        argocd-image-updater.argoproj.io/actual.helm.image-tag: actual.controllers.actual.containers.main.image.tag

        argocd-image-updater.argoproj.io/babybuddy.helm.image-name: babybuddy.controllers.babybuddy.containers.main.image.repository
        argocd-image-updater.argoproj.io/babybuddy.helm.image-tag: babybuddy.controllers.babybuddy.containers.main.image.tag

        argocd-image-updater.argoproj.io/meilisearch.helm.image-name: barlie.controllers.meilisearch.containers.main.image.repository
        argocd-image-updater.argoproj.io/meilisearch.helm.image-tag: barlie.controllers.meilisearch.containers.main.image.tag
        # argocd-image-updater.argoproj.io/meilisearch.helm.allow-tags: regexp:v\d+\.\d+\.(?!\d{2}\b)\d+(-[\w\d]+(?:\.[\w\d]+)*)?(\+[\w\d]+(?:\.[\w\d]+)*)?
        argocd-image-updater.argoproj.io/meilisearch.ignore-tags: "*"
        argocd-image-updater.argoproj.io/barlie-redis.helm.image-name: barlie.controllers.redis.containers.main.image.repository
        argocd-image-updater.argoproj.io/barlie-redis.helm.image-tag: barlie.controllers.redis.containers.main.image.tag
        argocd-image-updater.argoproj.io/barlie-assistant.helm.image-name: barlie.controllers.assistant.containers.main.image.repository
        argocd-image-updater.argoproj.io/barlie-assistant.helm.image-tag: barlie.controllers.assistant.containers.main.image.tag
        argocd-image-updater.argoproj.io/barlie-assistant.ignore-tags: "*"
        # argocd-image-updater.argoproj.io/barlie-assistant.helm.allow-tags: regexp:^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$
        argocd-image-updater.argoproj.io/barlie-sr.helm.image-name: barlie.controllers.salt-rim.containers.main.image.repository
        argocd-image-updater.argoproj.io/barlie-sr.helm.image-tag: barlie.controllers.salt-rim.containers.main.image.tag
        argocd-image-updater.argoproj.io/barlie-sr.ignore-tags: "*"
        # argocd-image-updater.argoproj.io/barlie-sr.ignore-tags: v\d+\.\d+

        argocd-image-updater.argoproj.io/changed.helm.image-name: changedetection.controllers.changedetection.containers.main.image.repository
        argocd-image-updater.argoproj.io/changed.helm.image-tag: changedetection.controllers.changedetection.containers.main.image.tag

        argocd-image-updater.argoproj.io/mealie.helm.image-name: mealie.controllers.mealie.containers.main.image.repository
        argocd-image-updater.argoproj.io/mealie.helm.image-tag: mealie.controllers.mealie.containers.main.image.tag

        argocd-image-updater.argoproj.io/sabnzbd.helm.image-name: sabnzbd.controllers.sabnzbd.containers.main.image.repository
        argocd-image-updater.argoproj.io/sabnzbd.helm.image-tag: sabnzbd.controllers.sabnzbd.containers.main.image.tag
        argocd-image-updater.argoproj.io/sabnzbd.update-strategy: digest

        argocd-image-updater.argoproj.io/sonarr.helm.image-name: sonarr.controllers.sonarr.containers.main.image.repository
        argocd-image-updater.argoproj.io/sonarr.helm.image-tag: sonarr.controllers.sonarr.containers.main.image.tag
        argocd-image-updater.argoproj.io/sonarr.update-strategy: digest
        # argocd-image-updater.argoproj.io/sonarr.helm.allow-tags: regexp:^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$

        argocd-image-updater.argoproj.io/radarr.helm.image-name: radarr.controllers.radarr.containers.main.image.repository
        argocd-image-updater.argoproj.io/radarr.helm.image-tag: radarr.controllers.radarr.containers.main.image.tag
        argocd-image-updater.argoproj.io/radarr.update-strategy: digest
        # argocd-image-updater.argoproj.io/radarr.helm.allow-tags: regexp:^(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)$

        argocd-image-updater.argoproj.io/receipt-fe.helm.image-name: receipt.controllers.frontend.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-fe.helm.image-tag: receipt.controllers.frontend.containers.main.image.tag
        argocd-image-updater.argoproj.io/receipt-api.helm.image-name: receipt.controllers.api.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-api.helm.image-tag: receipt.controllers.api.containers.main.image.tag
        argocd-image-updater.argoproj.io/receipt-db.helm.image-name: receipt.controllers.db.containers.main.image.repository
        argocd-image-updater.argoproj.io/receipt-db.helm.image-tag: receipt.controllers.db.containers.main.image.tag

        argocd-image-updater.argoproj.io/tautulli.helm.image-name: tautulli.controllers.tautulli.containers.main.image.repository
        argocd-image-updater.argoproj.io/tautulli.helm.image-tag: tautulli.controllers.tautulli.containers.main.image.tag

        argocd-image-updater.argoproj.io/donetick.helm.image-name: donetick.controllers.donetick.containers.main.image.repository
        argocd-image-updater.argoproj.io/donetick.helm.image-tag: donetick.controllers.donetick.containers.main.image.tag

      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: internal-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
      source:
        repoURL: git@github.com:erkerb4/home-k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'