apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-deployments
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:erkerb4/home-k8s-gitops.git
      revision: HEAD
      directories:
      - path: apps/prod-apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      annotations:
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/git-branch: main:image-updater-{{.SHA256}}
        argocd-image-updater.argoproj.io/image-list: overseerr=ghcr.io/linuxserver/overseerr:latest,vw=ghcr.io/dani-garcia/vaultwarden:~1

        notifications.argoproj.io/subscribe.app-outofsync.slack: argo
        notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
        notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: prod-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
      source:
        repoURL: git@github.com:erkerb4/home-k8s-gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'